substitutions:
  _REGION: asia-east1
  _REPOSITORY: nojv
  _COMPONENT: web
  _DOCKERFILE: infra/docker/web.Dockerfile

steps:
  - name: gcr.io/cloud-builders/docker:latest@sha256:6c9b879570fe1c63a78af0b575ca5ac52f6c2c7e25f76f91ae1f2d6cb2a872ee
    args:
      - build
      - --file
      - ${_DOCKERFILE}
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_COMPONENT}:${_SOURCE_SHA}
      - --label
      - org.opencontainers.image.revision=${_SOURCE_SHA}
      - --label
      - org.opencontainers.image.version=${_SOURCE_SHA}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_COMPONENT}:${_SOURCE_SHA}

serviceAccount: projects/$PROJECT_ID/serviceAccounts/${_SERVICE_ACCOUNT}

options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
