apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "nojv.namespace" . }}
  labels:
    name: {{ include "nojv.namespace" . }}
    {{- include "nojv.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "nojv.sandboxNamespace" . }}
  labels:
    name: {{ include "nojv.sandboxNamespace" . }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    {{- include "nojv.labels" . | nindent 4 }}
