{{- if .Values.pdb.enabled }}
{{- $names := list "web" "worker" "worker-platform" }}
{{- if .Values.registry.enabled }}
{{- $names = append $names "registry" }}
{{- end }}
{{- range $name := $names }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nojv.fullname" $ }}-{{ $name }}
  namespace: {{ include "nojv.namespace" $ }}
  labels:
    {{- include "nojv.labels" $ | nindent 4 }}
spec:
  maxUnavailable: {{ $.Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nojv-{{ $name }}
{{- end }}
{{- end }}
