{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nojv.fullname" . }}-worker
  namespace: {{ include "nojv.namespace" . }}
  labels:
    {{- include "nojv.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nojv-worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nojv.fullname" . }}-worker-platform
  namespace: {{ include "nojv.namespace" . }}
  labels:
    {{- include "nojv.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nojv-worker-platform
{{- end }}
