apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nojv.fullname" . }}-worker-judge
  namespace: {{ include "nojv.namespace" . }}
  labels:
    {{- include "nojv.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker-judge
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nojv.fullname" . }}-worker-platform
  namespace: {{ include "nojv.namespace" . }}
  labels:
    {{- include "nojv.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nojv.fullname" . }}-sandbox-job-manager
  namespace: {{ include "nojv.sandboxNamespace" . }}
  labels:
    {{- include "nojv.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nojv.fullname" . }}-worker-judge-sandbox-access
  namespace: {{ include "nojv.sandboxNamespace" . }}
  labels:
    {{- include "nojv.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nojv.fullname" . }}-sandbox-job-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "nojv.fullname" . }}-worker-judge
    namespace: {{ include "nojv.namespace" . }}
{{- if .Values.registry.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nojv.fullname" . }}-registry-gc-manager
  namespace: {{ include "nojv.namespace" . }}
  labels:
    {{- include "nojv.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nojv.fullname" . }}-worker-platform-registry-gc-access
  namespace: {{ include "nojv.namespace" . }}
  labels:
    {{- include "nojv.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nojv.fullname" . }}-registry-gc-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "nojv.fullname" . }}-worker-platform
    namespace: {{ include "nojv.namespace" . }}
{{- end }}
