apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: nojv-web
  namespace: flux-system
spec:
  image: ghcr.io/nojv-tw/nojv-web
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: nojv
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nojv-web
  filterTags:
    pattern: '^main-(?P<build>\d+)$'
    extract: "$build"
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: nojv
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nojv
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(deploy): update nojv image tag to {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./infra/flux
    strategy: Setters
