apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: temporal-server
  namespace: nojv-temporal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: temporal-postgres
  namespace: nojv-temporal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal-postgres
