// Mock data for assignments / exams / contests
window.CW_DATA = {
  course: {
    code: "CSIE 2025",
    name: "演算法設計",
    term: "Spring 2025 · Week 7",
    instructor: "Dr. Lin Yu-Hsuan",
    sectionHead: "第二學期 · 第七週",
  },

  assignments: [
    {
      id: "hw07",
      no: "07",
      title: "Sliding Window 進階",
      titleEn: "Advanced Sliding Window",
      summary: "六題與滑動視窗、單調佇列相關的題目。重點在 O(n) 處理區間極值與雙指針思路的混合應用。",
      tags: ["Two Pointers", "Monotonic Deque", "Prefix Sum"],
      problems: 6,
      solved: 3,
      score: 62,
      maxScore: 100,
      dueAt: "2025-03-21T23:59:00",
      status: "in_progress", // not_started | in_progress | submitted | graded
      submittedAt: null,
      releasedAt: "2025-03-14T09:00:00",
      attemptsAllowed: "unlimited",
      latePenalty: "每延遲 24 小時扣 10%",
      classAvg: 71,
      myRank: 18,
      classSize: 64,
    },
    {
      id: "hw06",
      no: "06",
      title: "Graph BFS / DFS",
      titleEn: "Graph Traversal Fundamentals",
      summary: "圖論第一波，建圖、走訪、連通分量、最短路徑（無權圖）。",
      tags: ["BFS", "DFS", "Connected Component"],
      problems: 5,
      solved: 5,
      score: 92,
      maxScore: 100,
      dueAt: "2025-03-14T23:59:00",
      status: "graded",
      submittedAt: "2025-03-13T22:14:00",
      releasedAt: "2025-03-07T09:00:00",
      attemptsAllowed: "unlimited",
      latePenalty: "每延遲 24 小時扣 10%",
      classAvg: 78,
      myRank: 7,
      classSize: 64,
    },
    {
      id: "hw08",
      no: "08",
      title: "區間 DP 入門",
      titleEn: "Interval DP Warm-up",
      summary: "三題引導式區間動態規劃，從矩陣鏈乘到回文切割。",
      tags: ["DP", "Interval"],
      problems: 3,
      solved: 0,
      score: 0,
      maxScore: 100,
      dueAt: "2025-03-28T23:59:00",
      status: "not_started",
      submittedAt: null,
      releasedAt: "2025-03-21T09:00:00",
      attemptsAllowed: "unlimited",
      latePenalty: "每延遲 24 小時扣 10%",
      classAvg: null,
      myRank: null,
      classSize: 64,
    },
    {
      id: "hw05",
      no: "05",
      title: "Greedy 排程",
      titleEn: "Greedy Scheduling",
      summary: "活動選擇、區間覆蓋、最小延遲排程。",
      tags: ["Greedy"],
      problems: 4,
      solved: 4,
      score: 88,
      maxScore: 100,
      dueAt: "2025-02-28T23:59:00",
      status: "graded",
      submittedAt: "2025-02-27T16:40:00",
      releasedAt: "2025-02-21T09:00:00",
      attemptsAllowed: "unlimited",
      latePenalty: "每延遲 24 小時扣 10%",
      classAvg: 74,
      myRank: 11,
      classSize: 64,
    },
    {
      id: "hw04",
      no: "04",
      title: "二分搜尋與抽象判定",
      titleEn: "Binary Search on Answer",
      summary: "把最佳化問題轉成可行性判定。練習邊界處理與單調性證明。",
      tags: ["Binary Search", "Monotonic"],
      problems: 4,
      solved: 4,
      score: 95,
      maxScore: 100,
      dueAt: "2025-02-21T23:59:00",
      status: "graded",
      submittedAt: "2025-02-21T18:02:00",
      releasedAt: "2025-02-14T09:00:00",
      attemptsAllowed: "unlimited",
      latePenalty: "每延遲 24 小時扣 10%",
      classAvg: 80,
      myRank: 4,
      classSize: 64,
    },
  ],

  exams: [
    {
      id: "midterm",
      code: "MID-2025-S",
      title: "期中考",
      subtitle: "Midterm Examination",
      summary: "範圍 W01–W07，分為四道大題與十二道小題。需於兩小時內完成。",
      durationMin: 120,
      problems: 6,
      maxScore: 100,
      startAt: "2025-03-25T13:00:00",
      endAt: "2025-03-25T15:00:00",
      status: "scheduled", // scheduled | open | in_progress | submitted | graded
      score: null,
      classAvg: null,
      myRank: null,
      classSize: 64,
      proctored: true,
      allowedLangs: ["C++17", "Python 3.11", "Java 17"],
      attemptsAllowed: 1,
      rules: [
        "全螢幕進行，切換視窗將被紀錄",
        "禁止複製貼上外部來源",
        "禁止開啟 AI 助理 / 翻譯",
        "可使用站內語言文件與 cppreference",
      ],
    },
    {
      id: "quiz03",
      code: "QZ-03",
      title: "隨堂小考 03",
      subtitle: "Pop Quiz · Greedy",
      summary: "兩道貪心題目，30 分鐘完成。",
      durationMin: 30,
      problems: 2,
      maxScore: 40,
      startAt: "2025-03-12T13:10:00",
      endAt: "2025-03-12T13:40:00",
      status: "graded",
      score: 34,
      classAvg: 26,
      myRank: 9,
      classSize: 64,
      proctored: true,
      allowedLangs: ["C++17", "Python 3.11"],
      attemptsAllowed: 1,
      rules: ["全螢幕進行", "禁止切換視窗", "禁止外部資源"],
    },
    {
      id: "final",
      code: "FIN-2025-S",
      title: "期末考",
      subtitle: "Final Examination",
      summary: "全範圍。三小時，八道題目，含一道創意題。",
      durationMin: 180,
      problems: 8,
      maxScore: 100,
      startAt: "2025-06-18T13:00:00",
      endAt: "2025-06-18T16:00:00",
      status: "scheduled",
      score: null,
      classAvg: null,
      myRank: null,
      classSize: 64,
      proctored: true,
      allowedLangs: ["C++17", "Python 3.11", "Java 17"],
      attemptsAllowed: 1,
      rules: [
        "全螢幕進行，切換視窗將被紀錄",
        "禁止複製貼上外部來源",
        "禁止開啟 AI 助理 / 翻譯",
        "可使用站內語言文件",
      ],
    },
  ],

  contests: [
    {
      id: "spring-cup",
      code: "SC25",
      title: "春季程式競賽 2025",
      subtitle: "Spring Cup · ICPC-style",
      summary: "三小時、五道題目、ICPC 賽制，計算 AC 數與罰時。",
      durationMin: 180,
      problems: 5,
      startAt: "2025-04-05T13:00:00",
      endAt: "2025-04-05T16:00:00",
      status: "upcoming", // upcoming | live | ended
      registered: true,
      participants: 142,
      registeredCount: 168,
      format: "ICPC",
      tags: ["公開賽", "ICPC 賽制", "獎金 NT$ 6,000"],
    },
    {
      id: "weekly-12",
      code: "WK12",
      title: "Weekly Round 12",
      subtitle: "每週小型賽 · 個人積分",
      summary: "九十分鐘、三道題目，依照 AC 時間排名。",
      durationMin: 90,
      problems: 3,
      startAt: "2025-03-20T19:30:00",
      endAt: "2025-03-20T21:00:00",
      status: "live",
      registered: true,
      participants: 87,
      registeredCount: 87,
      format: "Codeforces",
      tags: ["每週", "個人積分"],
    },
    {
      id: "div2-08",
      code: "D2-08",
      title: "Div. 2 Round #08",
      subtitle: "Codeforces-style · 個人計分",
      summary: "兩小時、四道題目。",
      durationMin: 120,
      problems: 4,
      startAt: "2025-03-08T20:00:00",
      endAt: "2025-03-08T22:00:00",
      status: "ended",
      registered: true,
      participants: 96,
      registeredCount: 110,
      format: "Codeforces",
      tags: ["Div. 2"],
      myRank: 23,
      mySolved: 3,
    },
  ],

  // detail content
  assignmentProblems: {
    hw07: [
      { id: "A", title: "最長無重複子字串", solved: true, score: 20, max: 20, tries: 3, difficulty: "Easy" },
      { id: "B", title: "K 個距離內最大值", solved: true, score: 18, max: 20, tries: 5, difficulty: "Medium" },
      { id: "C", title: "可行子陣列之和", solved: true, score: 24, max: 30, tries: 7, difficulty: "Medium" },
      { id: "D", title: "雙序列窗口和", solved: false, score: 0, max: 15, tries: 4, difficulty: "Medium" },
      { id: "E", title: "最小覆蓋子串", solved: false, score: 0, max: 10, tries: 2, difficulty: "Hard" },
      { id: "F", title: "滑動中位數", solved: false, score: 0, max: 5, tries: 0, difficulty: "Hard" },
    ],
  },
  examProblems: {
    midterm: [
      { id: "I",   title: "Hash & Counting",    points: 10, difficulty: "Easy" },
      { id: "II",  title: "Sorting Variants",   points: 15, difficulty: "Easy" },
      { id: "III", title: "Binary Search",      points: 15, difficulty: "Medium" },
      { id: "IV",  title: "Greedy Scheduling",  points: 20, difficulty: "Medium" },
      { id: "V",   title: "Graph BFS",          points: 20, difficulty: "Medium" },
      { id: "VI",  title: "Interval DP",        points: 20, difficulty: "Hard" },
    ],
  },
  contestProblems: {
    "spring-cup": [
      { id: "A", title: "Warm Bread", difficulty: "Easy",   solvedBy: 0 },
      { id: "B", title: "Two Towers", difficulty: "Easy",   solvedBy: 0 },
      { id: "C", title: "River Crossing", difficulty: "Medium", solvedBy: 0 },
      { id: "D", title: "Spice Route", difficulty: "Medium", solvedBy: 0 },
      { id: "E", title: "Citadel", difficulty: "Hard",    solvedBy: 0 },
    ],
    "weekly-12": [
      { id: "A", title: "Bell Toss", difficulty: "Easy", solvedBy: 71 },
      { id: "B", title: "Knapsack Lite", difficulty: "Medium", solvedBy: 38 },
      { id: "C", title: "Train Network", difficulty: "Hard", solvedBy: 9 },
    ],
  },

  // Exam class results (teacher / TA only)
  examClassResults: {
    midterm: {
      problems: [{id:"1",title:"計算相鄰差絕對值",max:30},{id:"2",title:"二分搜尋進階",max:35},{id:"3",title:"連通分量",max:35}],
      classAvg: 71.4, median: 74, max: 98, min: 22, submitted: 38, total: 42,
      rows: [
        { rank: 1, user:"ada_lin",      sid:"B11401001", total:98, scores:[30,33,35] },
        { rank: 2, user:"kuro_taro",    sid:"B11401002", total:94, scores:[28,33,33] },
        { rank: 3, user:"minty.fox",    sid:"B11401005", total:91, scores:[30,30,31] },
        { rank: 4, user:"joon_park",    sid:"B11401008", total:88, scores:[28,30,30] },
        { rank: 5, user:"you_are_here", sid:"B11401034", total:86, scores:[28,30,28], me:true },
        { rank: 6, user:"noctilucent",  sid:"B11401011", total:84, scores:[27,28,29] },
        { rank: 7, user:"rye.cipher",   sid:"B11401014", total:80, scores:[27,28,25] },
        { rank: 8, user:"kappa.k",      sid:"B11401017", total:76, scores:[25,27,24] },
        { rank: 9, user:"ember.q",      sid:"B11401019", total:71, scores:[24,25,22] },
        { rank:10, user:"soba.dev",     sid:"B11401021", total:67, scores:[22,24,21] },
        { rank:11, user:"chen_yh",      sid:"B11401024", total:62, scores:[20,22,20] },
        { rank:12, user:"wang_pl",      sid:"B11401026", total:54, scores:[18,20,16] },
        { rank:13, user:"liu_kc",       sid:"B11401028", total:46, scores:[15,18,13] },
        { rank:14, user:"tsai_my",      sid:"B11401030", total:38, scores:[12,16,10] },
        { rank:15, user:"hsu_jw",       sid:"B11401032", total:22, scores:[8,10,4] },
      ],
      submissions: [
        { user:"ada_lin", time:"15:48", problem:"3", verdict:"AC", score:35 },
        { user:"kuro_taro", time:"15:45", problem:"3", verdict:"AC", score:33 },
        { user:"liu_kc", time:"15:42", problem:"2", verdict:"WA", score:0 },
        { user:"you_are_here", time:"15:39", problem:"3", verdict:"AC", score:28 },
        { user:"minty.fox", time:"15:35", problem:"3", verdict:"AC", score:31 },
        { user:"tsai_my", time:"15:31", problem:"1", verdict:"TLE", score:0 },
      ],
    },
  },

  // Student's own exam review (per-problem outcome for replay page)
  examReview: {
    midterm: {
      total: 86, max: 100,
      problems: [
        { id:"1", title:"計算相鄰差絕對值", max:30, score:28, verdict:"AC", tries:2, language:"C++17", subtasks:[{w:40,pass:true},{w:60,pass:true}], note:"頭尾邊界漏採一個 case" },
        { id:"2", title:"二分搜尋進階", max:35, score:30, verdict:"PAC", tries:3, language:"C++17", subtasks:[{w:30,pass:true},{w:40,pass:true},{w:30,pass:false}], note:"子任務 3 TLE" },
        { id:"3", title:"連通分量", max:35, score:28, verdict:"PAC", tries:4, language:"C++17", subtasks:[{w:50,pass:true},{w:50,pass:false}], note:"兩次 WA、一次 RE" },
      ],
    },
  },

  scoreboard: {
    "spring-cup": {
      format: "ICPC",
      problems: [
        { id: "A", title: "Bell Toss" },
        { id: "B", title: "Knapsack Lite" },
        { id: "C", title: "Train Network" },
        { id: "D", title: "Crystal Lattice" },
        { id: "E", title: "Origami Walk" },
      ],
      // ICPC row: per-problem { t (first AC time), tries, ok, fb (first blood) }
      rows: [
        { rank: 1, user: "ada_lin",      solved: 5, penalty: 412, cells: [{t:"00:14",tries:1,ok:true,fb:true},{t:"00:38",tries:1,ok:true},{t:"01:12",tries:2,ok:true},{t:"02:01",tries:1,ok:true,fb:true},{t:"02:48",tries:3,ok:true}] },
        { rank: 2, user: "kuro_taro",    solved: 5, penalty: 487, cells: [{t:"00:18",tries:2,ok:true},{t:"00:45",tries:1,ok:true,fb:true},{t:"01:21",tries:1,ok:true,fb:true},{t:"02:18",tries:2,ok:true},{t:"02:55",tries:2,ok:true}] },
        { rank: 3, user: "you_are_here", solved: 4, penalty: 364, cells: [{t:"00:21",tries:1,ok:true},{t:"00:52",tries:1,ok:true},{t:"01:34",tries:3,ok:true},{t:"02:24",tries:2,ok:true},{t:"—",tries:4,ok:false}], me: true },
        { rank: 4, user: "minty.fox",    solved: 4, penalty: 401, cells: [{t:"00:19",tries:1,ok:true},{t:"00:58",tries:2,ok:true},{t:"01:47",tries:1,ok:true},{t:"—",tries:5,ok:false},{t:"02:38",tries:1,ok:true,fb:true}] },
        { rank: 5, user: "joon_park",    solved: 3, penalty: 247, cells: [{t:"00:22",tries:1,ok:true},{t:"01:04",tries:2,ok:true},{t:"01:58",tries:2,ok:true},{t:"—",tries:3,ok:false},{t:"—",tries:0,ok:false}] },
        { rank: 6, user: "noctilucent",  solved: 3, penalty: 288, cells: [{t:"00:27",tries:2,ok:true},{t:"01:14",tries:1,ok:true},{t:"02:08",tries:3,ok:true},{t:"—",tries:1,ok:false},{t:"—",tries:0,ok:false}] },
        { rank: 7, user: "rye.cipher",   solved: 3, penalty: 312, cells: [{t:"00:24",tries:1,ok:true},{t:"01:22",tries:3,ok:true},{t:"02:21",tries:2,ok:true},{t:"—",tries:4,ok:false},{t:"—",tries:0,ok:false}] },
        { rank: 8, user: "kappa.k",      solved: 2, penalty: 168, cells: [{t:"00:29",tries:1,ok:true},{t:"01:38",tries:2,ok:true},{t:"—",tries:5,ok:false},{t:"—",tries:0,ok:false},{t:"—",tries:0,ok:false}] },
        { rank: 9, user: "ember.q",      solved: 2, penalty: 195, cells: [{t:"00:31",tries:2,ok:true},{t:"01:51",tries:1,ok:true},{t:"—",tries:0,ok:false},{t:"—",tries:3,ok:false},{t:"—",tries:0,ok:false}] },
        { rank: 10,user: "soba.dev",     solved: 1, penalty:  44, cells: [{t:"00:44",tries:2,ok:true},{t:"—",tries:3,ok:false},{t:"—",tries:1,ok:false},{t:"—",tries:0,ok:false},{t:"—",tries:0,ok:false}] },
      ],
    },
    "weekly-12": {
      format: "Codeforces",
      problems: ["A", "B", "C"],
      rows: [
        { rank: 1,  user: "ada_lin",     score: 1840, solved: [{ t: "00:08", points: 500, ok: true }, { t: "00:24", points: 740, ok: true }, { t: "01:02", points: 600, ok: true }] },
        { rank: 2,  user: "kuro_taro",   score: 1690, solved: [{ t: "00:11", points: 470, ok: true }, { t: "00:31", points: 700, ok: true }, { t: "01:18", points: 520, ok: true }] },
        { rank: 3,  user: "you_are_here",score: 1420, solved: [{ t: "00:14", points: 460, ok: true }, { t: "00:42", points: 660, ok: true }, { t: "—",     points: 300, ok: false, tries: 2 }], me: true },
        { rank: 4,  user: "minty.fox",   score: 1380, solved: [{ t: "00:09", points: 480, ok: true }, { t: "00:48", points: 620, ok: true }, { t: "—",     points: 280, ok: false, tries: 3 }] },
        { rank: 5,  user: "joon_park",   score: 1290, solved: [{ t: "00:16", points: 450, ok: true }, { t: "00:55", points: 590, ok: true }, { t: "—",     points: 250, ok: false, tries: 1 }] },
        { rank: 6,  user: "noctilucent", score: 1150, solved: [{ t: "00:21", points: 430, ok: true }, { t: "01:04", points: 540, ok: true }, { t: "—",     points: 180, ok: false, tries: 2 }] },
        { rank: 7,  user: "rye.cipher",  score: 1080, solved: [{ t: "00:18", points: 440, ok: true }, { t: "01:11", points: 520, ok: true }, { t: "—",     points: 120, ok: false, tries: 4 }] },
        { rank: 8,  user: "kappa.k",     score:  950, solved: [{ t: "00:22", points: 420, ok: true }, { t: "01:18", points: 460, ok: true }, { t: "—",     points: 70,  ok: false, tries: 1 }] },
        { rank: 9,  user: "ember.q",     score:  820, solved: [{ t: "00:24", points: 410, ok: true }, { t: "01:24", points: 410, ok: true }, { t: "—",     points: 0,   ok: false, tries: 0 }] },
        { rank: 10, user: "soba.dev",    score:  700, solved: [{ t: "00:27", points: 400, ok: true }, { t: "—",     points: 0,   ok: false, tries: 3 }, { t: "—", points: 300, ok: false, tries: 1 }] },
      ],
    },
  },

  // current "you"
  me: {
    name: "Hsieh Yi-Chun",
    handle: "you_are_here",
    studentId: "B11401034",
  },
};
