apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: nojv-migrator
spec:
  template:
    template:
      metadata:
        annotations:
          run.googleapis.com/cloudsql-instances: PROJECT_ID:REGION:INSTANCE
          run.googleapis.com/vpc-access-connector: VPC_CONNECTOR_NAME
          run.googleapis.com/vpc-access-egress: private-ranges-only
      spec:
        containers:
          - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/migrator:latest
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    key: latest
                    name: nojv-database-url
        maxRetries: 1
        taskCount: 1
