apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nojv-web
spec:
  template:
    spec:
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/web:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: nojv-database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: nojv-redis-url
