-- Phase 5 cleanup: drop TestcaseSet.isHidden.
--
-- If you are upgrading from pre-Phase-1 data where samples were
-- represented as `isHidden = false` testcase sets, run the following
-- SQL FIRST to hoist them into Problem.samples:
--
--     UPDATE "Problem" p
--     SET "samples" = sub.samples
--     FROM (
--       SELECT ts."problemId",
--              jsonb_agg(jsonb_build_object(
--                'stdin', tc."stdin",
--                'expected', COALESCE(tc."expectedStdout", '')
--              ) ORDER BY tc."ordinal") FILTER (WHERE tc.id IS NOT NULL) AS samples
--       FROM "TestcaseSet" ts
--       LEFT JOIN "Testcase" tc ON tc."testcaseSetId" = ts.id
--       WHERE ts."isHidden" = false
--       GROUP BY ts."problemId"
--     ) sub
--     WHERE p.id = sub."problemId"
--       AND (p."samples" IS NULL OR jsonb_array_length(p."samples") = 0);
--
--     DELETE FROM "TestcaseSet" WHERE "isHidden" = false;
--
-- Then apply this migration. Once applied, the DB has no way to
-- distinguish sample sets from graded sets — all remaining TestcaseSet
-- rows are treated as graded subtasks.

ALTER TABLE "TestcaseSet" DROP COLUMN IF EXISTS "isHidden";
